// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home(isAdmin bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"relative w-full h-[60vh] bg-background overflow-hidden flex items-center justify-center\"><div class=\"absolute inset-0 bg-accent z-10\"></div><div class=\"z-20 text-center px-4\"><h1 class=\"text-4xl md:text-6xl font-bold text-primary mb-4 shadow-lg\">TO PROVIDE QUALITY EDUCATION</h1><h2 class=\"text-2xl md:text-3xl text-secondary\">TO ALL SCHEDULED TRIBES STUDENTS</h2></div></section><div class=\"bg-primary text-sm py-2 border-y border-border px-4 overflow-hidden\"><p class=\"text-primary-foreground whitespace-nowrap animate-marquee\">New Admissions Open for 2026-2027 Academic Year • Latest Notification Regarding Exams...</p></div><section class=\"max-w-7xl mx-auto py-16 px-4 sm:px-6 grid grid-cols-1 md:grid-cols-2 gap-12 items-center\"><div class=\"grid grid-cols-2 gap-2\"><div class=\"bg-background-700 h-40 rounded-tl-3xl\"></div><div class=\"bg-background-600 h-40 rounded-tr-3xl\"></div><div class=\"bg-background-600 h-40 rounded-bl-3xl\"></div><div class=\"bg-background-700 h-40 rounded-br-3xl\"></div></div><div><h3 class=\"text-3xl font-bold mb-4\">About us</h3><p class=\"text-foreground leading-relaxed\">Ekalavya Model Residential School (EMRS) is established to provide quality education...</p></div></section><section class=\"bg-accent py-16\"><div class=\"max-w-7xl mx-auto px-4 sm:px-6 grid grid-cols-1 md:grid-cols-2 gap-12\"><div><h3 class=\"text-2xl font-bold mb-4 text-primary\">VISION</h3><p class=\"text-accent-foreground\">To nurture individuals with academic excellence and core values...</p></div><div><h3 class=\"text-2xl font-bold mb-4 text-primary\">MISSION</h3><p class=\"text-accent-foreground\">To create a conducive learning environment that empowers students...</p></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = BaseLayout("EMRS - Home", isAdmin).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
